sudo: false
language: java
jdk:
- oraclejdk9
cache:
  directories:
  - "$HOME/.cache"
maven:
  version: 3.5.2
deploy:
  provider: script
  script: cp settings.xml $HOME/.m2/settings.xml && mvn deploy -Prelease
  skip_cleanup: true
#  on:
#    tags: true
env:
  global:
    - secure: "eScNIuw7+Nz3577nFE3BsN+MvIsr4OIuMSFAstEX+/tPt5FUltvc+LhMxyPiRjHPqq7MlePAtNqm5aqGKr0SZVUjGEvSGrisxG10JvnUjYiBz8lB/LROSwI8Y5h8RFQu9aKiTuYjw5VcIPj47zG1Xd3v7r9ooEeC4cSh+y+9Wedyro3J+DFwGkUoNHRFilPU/cd/Lx2cFPWjGV4rk1yXS+ElSa34PU2UNBRZU+bM5sN0GuMU9MHCrhsvgeSPRaWAEMVHIUtXkHAeQyqvQQKNkOCUmLCHkHtNT1+cREQ5q3wrZcXdZHpVzYj4kdPRChp1BOOMYjtfFajZKZJrQTlgT8SmNYjml9adb6K0aQdwG130u0W0wf4zPAzo5+ai7IXq3dWB8hHT6t9zAl9on9ZZVzgfNTS6OZ0lrceM80CqqO76YxMECm5sYHMgkY2gVgXxkI/T9DnAnBZfeGb4cCd7ZqtpNAT1fjJsYh9vAw4CnmhaeZb9xvJHzTGy2+ljsG4orvTCEKA6kpYeCioT/ybTtPlDGs3lmehlb6RcdBIlTCT6E6H8nT0Dk6AokDn0r1RH0FFqQA4RSJxXSWC1Wl3RTgzLnCaI0LxuEVUtXN+8fEuIE6b91jrlOo3eLTJGLgxjX728FEzD4NbPBJjRBU9RH/5KxIMhVzgWiU6obH0cd1I="
    - secure: "AAKxYTg0xbAbVYm2nuXjLEe04K9HsE13PKJNIpSdJlRPddl3AGxpD2vAGuk+53UNocapGIytyfSpRw9gYxHukVoFcgq/hDn2gPYzd3J50PP21/hszb7czJULKyCjEA9xQymNLarmlLozKZIQihi1wDGtU9mulDSMXoYn7AJuWVDddYp+lb5pU/+AWxZbEXoqPcOuaZL5YpNxsJ3azXI84fKgoc5Jec0kj0FA5iMpu8hiSdVW1IDbY8gRQroUtlRou5O97UGIaKtPawS9qGfYn6QS+CWNjoaXCdB0mYWpToQp6kCQdjjalFSNehgxpGi2w8tvcU4mYqLLf/aDcubIMS3rwBgLp4wXGu59yhZk0Exn99NLpSmV9M8PeVxLq0t6GAOvPbiDQVLL5l14SuZvqKWY/jyosuywKUP9T4RmdErhQauQVQ7S/lkLW1ATZ3yfEXpJ1HPflawbRsrU5LbUXOhmYCNfUuW3bnMRgypKMURT26L7CAriQWSY2fBsAph4a/niKQt2lOWSJJcK3lDO/Kk8Hm9ASgotyqpia1z7sPzE0HNOsOflO+aHXwFIIq3ibKdy0XxsdE4nNhGRvsMa1h6RvWYVqnwQWDo7/QiGxBtFjGOXrop1oWhnznMmD3P+0xHxGc6HTq1NYc1i7mktjgbz3RtjIs0rb15f1j2ax6c="
    - MAVEN_HOME=/usr/local/maven-3.5.2