sudo: false
language: java
jdk:
- oraclejdk9
cache:
  directories:
  - "$HOME/.cache"
maven:
  version: 3.5.2
deploy:
  provider: script
  script: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -Prelease
  skip_cleanup: true
#  on:
#    tags: true
env:
  global:
    - secure: dRd2tDAIqcvTCbnDrPAM+cEHn6GF7uVlnM0Cly/Mj+W75Wph0rMiPJwuoAgAU3Mbv7jmbZex5c1LXcbPAVqzpkXVZioLq1TN0tZ+ZH1le6afrzZIBLhzH7k0i8X+xuacLwxq93qsrIhsvqOx+zSKsT2fgGRi7pN97lPiE1UaySWBntYGEZNUBjYnvH6TFuf+ceNvTUXOxl1BoSogDOeIDU7D+Xq41DzQf7/3OwE/Q1iMgKwZKV+WMdhgfv8TgCAEb/bhW0VzdQZqyjpbjcy/2GRU/aKK022SaSF6eC2vUkwRQRsFc2LQAmiyL5CmyHBeGZFaDs9vs4Y1HNUW8tfpt8HrNXgXuN4HOHC9BiQzIOeS+qlQ9cGRTeVVKTuo8GEHlKqiwxJm6Xap0e6k7gS3nEw9nlFYi7oPNGIS6kff9ouuDY4NnIG2mUYMQUHuR4erhZdCjOgzVjB5AQ/C+iFd3EiWML6jB7oVOxH4E6peoajppMX4hCcEP7tNSFqTYfCzxfQgxQqNCiNnrIjp8Rwcd/KlMZ8t5oqRtBzmd7494RTcz2DteF3tiqzlAWUfe2ZUHX7VtMsBnpqMLwvXUEzIWV71I9AZpDH586/R3jQQQzYgAgiVL+lTSJg7LazPagZMKwuARsUxCljQMV3yR5dgiQaij3XV79krBauPmnI0DAc=
    - secure: F8TXuH4oyeKoubGuCpgXS0bRvWpY7eMgI9Qhw0/jg0hHVJTWYYJAO4Fmdmy0MohNJBsr2jY4Nx1yMoodORphLhM34allpGZl6mLdUyLF752zqAZ5+JdhBppsykO3NAkI02+mJEOsfuNYwyMab7O9JlCwSYIYs7xLZBPxs0xtaQZyqAajiPRXvZSau/C3G8WuBtc7MSqR3w0kC0U+ZonAjqzjVjLVIyQBW4m75F+sUv4cEV8kKbvPYJd4WXKIjV+SVaKcNgn+8mrFw7P2tkX2lH4Lv984/76VlRiEk6WBvWcxMJ/Clj5axHr/owTVY31aukOY1uL7ZrkjPIMLV1I2tXvUyj9MRGG82G6xUewWQXtZMsHuX7t1mT+12PYRyARfU5UXxFdivzeHdB/d7R+Vp8ea0hGv0eEqHEtrNj04c5FvlkXgyPEoztlPV8cLa6b7A/gHcWRyepMJFQy1Nu6nsMKPCIkm6ciBryLhujkfOOOjpwReF2NIUiLp0KUadXchT2umTDobkTgmlCoupQlqFlXagQKYd0+j+q537VeiPD59AeR6NiNsVYpOkxUwWsuFSUexnkC6I76A9nvDkats/xgvF5nMNBkhBgtefhqNICoNkVV3jhN7HLUQmm8s9pQDKxxYXlArPxHNJFSdDw6J6hhgq9sBey8X4SgMsNGzC7s=
    - MAVEN_HOME=/usr/local/maven-3.5.2