sudo: false
language: java
jdk:
  - oraclejdk9

cache:
  directories:
  - "$HOME/.cache"

maven:
  version: 3.5.2

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true

env:
  - MAVEN_HOME=/usr/local/maven-3.5.2